//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPratico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Colaborador
    {
        public int id { get; set; }
        public string Nome { get; set; }
        [Required]
        [Display(Name = "CPF")]
        public string cpf { get; set; }
        public string rg { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public Nullable<int> estadoCivil { get; set; }
        public string paginaPessoal { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public Nullable<bool> ativo { get; set; }
        public Nullable<int> funcao { get; set; }
    }
}
