//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPratico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Competencia
    {
        public int id { get; set; }
        [Required]
        [Display(Name = "Descrição")]
        public string descricao { get; set; }
        [Required]
        [Display(Name = "Categoria Superior")]
        public Nullable<int> id_superior { get; set; }
        [Required]
        [Display(Name = "Ativo")]
        public Nullable<Boolean> ativo { get; set; }
    }
}
