//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoPratico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Usuario
    {
        public int id { get; set; }
        [Required]
        [Display(Name = "Nome")]
        public string Nome { get; set; }
        [Required]
        [Display(Name = "CPF")]
        public string cpf { get; set; }
        [Required]
        [Display(Name = "RG")]
        public string rg { get; set; }
        [Display(Name = "Telefone")]
        public string telefone { get; set; }
        [Required]
        [Display(Name = "Email")]
        public string email { get; set; }
        [Display(Name = "Estado Civil")]
        public Nullable<int> estadoCivil { get; set; }
        [Display(Name = "Pagina pessoal")]
        public string paginaPessoal { get; set; }
        [Required]
        [Display(Name = "Login")]
        public string login { get; set; }
        [Required]
        [Display(Name = "Senha")]
        [DataType(DataType.Password)]
        public string senha { get; set; }
        [Required]
        [Display(Name = "Ativo")]
        public Nullable<Boolean> ativo { get; set; }
        [Required]
        [Display(Name = "Função")]
        public Nullable<int> funcao { get; set; }
    }
}
